export const LOGIN_AUTENTHICATED = 'LOGIN_AUTENTHICATED'
export const USER_AUTHENTICATION = 'USER_AUTHENTICATION'
export const LOGOUT = 'LOGOUT'

export const GET_CATEGORIES = 'GET_CATEGORIES'
export const ADD_CATEGORY = 'ADD_CATEGORY'
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY'
export const DELETE_CATEGORY = 'DELETE_CATEGORY'

export const GET_STATES = 'GET_STATES'
export const ADD_STATE = 'ADD_STATE'
export const UPDATE_STATE = 'UPDATE_STATE'
export const DELETE_STATE = 'DELETE_STATE'

export const GET_MEDIOS = 'GET_MEDIOS'
export const ADD_MEDIO = 'ADD_MEDIO'
export const UPDATE_MEDIO = 'UPDATE_MEDIO'
export const DELETE_MEDIO = 'DELETE_MEDIO'

export const GET_MODULES = 'GET_MODULES'
export const ADD_MODULE = 'ADD_MODULE'
export const UPDATE_MODULE = 'UPDATE_MODULE'
export const DELETE_MODULE = 'DELETE_MODULE'

export const GET_SOLUTIONS = 'GET_SOLUTIONS'
export const ADD_SOLUTION = 'ADD_SOLUTION'
export const UPDATE_SOLUTION = 'UPDATE_SOLUTION'
export const DELETE_SOLUTION = 'DELETE_SOLUTION'

export const GET_TICKETS = 'GET_TICKETS'
export const REGISTER_TICKET = 'REGISTER_TICKET'
export const RELOADER_DATA = 'RELOADER_DATA'
export const ALL_TICKETS = 'ALL_TICKETS'
export const ASSIGN_TICKET = 'ASSIGN_TICKET'
export const ASSIGNMENTS_TICKET = 'ASSIGNMENTS_TICKET'
export const COMMENTARY_RELOAD = 'COMMENTARY_RELOAD'

export const GET_NOTIFICATION = 'GET_NOTIFICATION'
export const NOTIFICATION_MARKALL = 'NOTIFICATION_MARKALL'

export const RELOAD = 'RELOAD'
export const REGISTER_USER = 'REGISTER_USER' 